import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="antialiased">
      <body className={inter.className}>
        <div className="bg-[#25282e]">
          <header className="h-28 w-full bg-[#25282e] px-4 py-7">
            <div className="item-center mx-auto flex max-w-7xl justify-between py-4">
              <div className="text-zinc-900">
                <button className="relative h-[24px] w-[50px] rounded-sm border-x-transparent bg-white before:absolute before:-top-[13px] before:left-0 before:h-0 before:w-0 before:border-x-[25px] before:border-b-[14px] before:border-x-transparent before:border-b-white after:absolute after:-bottom-[13px] after:left-0 after:h-0 after:w-0 after:border-x-[25px] after:border-t-[14px] after:border-x-transparent after:border-t-white">
                  <span>|</span>
                  <span>I</span>
                  <span>|</span>
                </button>
              </div>
              <nav className="text-md flex list-none gap-12 text-white">
                <li>Feature</li>
                <li>Pricing</li>
                <li>FAQ</li>
                <li>Downloads</li>
              </nav>
              <div className="text-md text-white">dark</div>
            </div>
          </header>
          {children}
        </div>
      </body>
    </html>
  )
}

//  content: "";
//  position: absolute;
//  top: -25px;
//  left: 0;
//  width: 0;
//  height: 0;
//  border-left: 50px solid transparent;
//  border-right: 50px solid transparent;
//  border-bottom: 25px solid red;
